// ...existing code...
const moduleA = require('./moduleA');
const moduleB = require('./moduleB');
const someModule = require('./someModule');
// ...existing code...
const anotherModule = require('./anotherModule');
// ...existing code...
